### ISSUE TITLE
Allow to turn on SSO only login for the wiki

### ISSUE THREAD

**Issue by oanat** [xwikisas/integration-azure-oauth#10]
For the moment users need to click a button to Login with Azure AD. 
We have received requests to enable the Azure SSO directly. 
We could add a configuration option for the application to force SSO with a "hidden" option to bypass it for superadmin.

**Comment by polx** [comment]
That seems like an enhancement that would be done at the settings side (xwikiclass, velocity) and in the login-code produced HTML.
I like a wording such as "jump-to-sso-immediately" (skip is really misunderstandable).

Note that using this would prevent SSO to work with several providers. A plan made for the future.

**Comment by lucaa** [comment]
> Note that using this would prevent SSO to work with several providers. 

You mean having _multiple_ identity providers, like multiple Azure ADs to choose from? Is that even an option?
Or just the 2 providers XWiki and Azure? - knowing that, indeed, the XWiki login UI does not necessarily mean XWiki Identity provider, it can also be LDAP or OpenIDC, for example.

As an answer to the initial remark: of course it will not work with multiple providers, it's the whole idea to not have to ask yourself about how to login...

**Comment by polx** [comment]
I do mean multiple providers. Google and Azure would can work out of the book (google is not yet released).

**Comment by lucaa** [comment]
> I do mean multiple providers. Google and Azure would can work out of the book (google is not yet released).

ok, but this is true if they all implement the same stategy of not being activated always by default but asking the question to the user...

**Comment by polx** [comment]
I guess the proper strategy is that the identity-oauth admin panels should all check that only a single one is active if the "auto-jump-to-sso" setting is true.
There was the API for a validation but it has not been used, all of it was done in the client.

**Comment by lucaa** [comment]
yeah, I understood now that you meant multiple _oauth_ providers, which makes sense indeed in the context of implementation of this authenticator, based on a generic oauth authentication framework that could have multiple authenticators installed on the same wiki.

**Comment by polx** [comment]
Right.
Please don't call them authenticators as this is taken by the auth-providers of XWiki in the common language. Providers, or better, identity provider, makes it clearer.

**Comment by polx** [comment]
Right. However, that'd mean we have a URL "that does not jump" that shows xwiki's login. That's new.

**Comment by lucaa** [comment]
> that'd mean we have a URL "that does not jump" that shows xwiki's login. That's new.

Either I don't understand what "jumping/not jumping" means, or I don't see how that is new.

> force SSO with a "hidden" option to bypass it for superadmin.

For me this :arrow_up means that there is a bypass URL that superadmin can use to login using standard XWiki authentication to fill in their user and password and get authenticated. Superadmin would need to _know_ that URL or URL parameters, there would be no option on the UI. Thus, this was part of the requirements from the very beginning and it's not 'new', for me.

**Comment by polx** [comment]
Sure sure... it's just not there yet but I guess you're right that this is included in the requested change.

**Comment by lucaa** [comment]
I made a hack patch for this recently and the way I did it is that, in the Oauth LoginUIX here https://github.com/xwikisas/identity-oauth/blob/master/ui/src/main/resources/IdentityOAuth/LoginUIExtension.vm#L42 when no parameter was set and when no bypass was signaled, I redirected to ?identityOAuth=start with some hardcoded provider parameters.

My code specifically is this, in case anyone else needs it:
```
 #elseif ("$!request.bypassazure" != "true")
   #set($statusMsg = "Redirect to azure login")
  #set($currentLocation = "$request.requestURL?$!request.queryString")
  #set($authQueryString = "&identityOAuth=start&provider=AzureAD&browserLocation=$escapetool.url($currentLocation)")
  #set($discard = $response.sendRedirect($xwiki.getURL('XWiki.XWikiLogin', 'login', $authQueryString)))
```

This gave me an idea: if we could at least implement, in identity-oauth, that it shouldn't show XWiki auth and then, if there are no oauth providers to choose from (which is 95% of the cases), it would use the one and only and redirect automatically to its login, like I did above (except that I hardcoded the provider).
If there are providers to choose from, it would display them in a list, like it does today, and the presence of the XWiki login in this list would be determined by that first flag.

**Comment by oanalavinia** [comment]
This will be fixed as part of https://github.com/xwikisas/identity-oauth/issues/19

**Comment by oanalavinia** [comment]
Fixed as part of https://github.com/xwikisas/identity-oauth/issues/19 in https://github.com/xwikisas/integration-azure-oauth/commit/bc1ccd226fd1594a95a8be27e55740b9f8f0eba1
