### ISSUE TITLE
Login option is shown after uninstalling the Microsoft Azure Active Directory Single Sign-On (SSO) (Pro)

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/integration-azure-oauth#12]
After uninstalling the Microsoft Azure Active Directory Single Sign-On (SSO) (Pro) this is how the login looks:
![image](https://user-images.githubusercontent.com/36840106/174065540-05df425b-df52-4318-ba14-e236b9a7a167.png)

When looking at the Global Administration > Extensions > Licenses table, we can see **Configuration Pages for Microsoft Azure Active Directory Single Sign-On (SSO) (Pro)**.

After uninstalling it this is how the login page looks:
![image](https://user-images.githubusercontent.com/36840106/174065838-0facea72-da72-43e9-b09d-4f73466d84f2.png)

Checking again the Licenses table, we can see **Identity OAuth (Pro)** and **Microsoft Azure Active Directory Single Sign-On (SSO) (pro) API** .
![image](https://user-images.githubusercontent.com/36840106/174066012-a3f8eb6f-62a5-4f09-a3d4-3a810bb8219c.png)

After uninstalling **Microsoft Azure Active Directory Single Sign-On (SSO) (pro) API** this is how the login looks:

![image](https://user-images.githubusercontent.com/36840106/174066187-e5a2c8b2-68f3-444b-a33a-eaccd1e2adb9.png)

After uninstalling **Identity OAuth (Pro)** the AzureAD login option has disappeared.
![image](https://user-images.githubusercontent.com/36840106/174066339-dd4f8233-166e-4645-8ca1-4c1efc5e81fe.png)

However, after a while, when going on the login page there is a warning shown again:
![image](https://user-images.githubusercontent.com/36840106/174069791-ef8c98de-daf1-4173-9f42-f0bdaafcfd73.png)

There is one more dependency extension listed - **Identity OAuth Integration (API)** - in the Licenses table.
![image](https://user-images.githubusercontent.com/36840106/174070003-da4a30c7-af62-4d8f-888b-9a3e5544303e.png)

When trying to login with the XWiki credentials, I am redirected to another login page with the URL https://tryazureadapp.demo.xwiki.com/xwiki/bin/loginsubmit/XWiki/XWikiLogin
![image](https://user-images.githubusercontent.com/36840106/174070422-26dd51db-0eea-4b1b-af6e-2199adb83ab3.png)

Even if I enter my XWiki credentials, the login is not done. I needed to restart the instance to have again access to the wiki.

After the restart, here is how the login page looks, with a Broken Azure AD option:
![image](https://user-images.githubusercontent.com/36840106/174077410-2bc5057e-200a-48d0-8dc1-adb1c24ea4af.png)

Now, I'm able to login using the XWiki account credentials.

Going on the Global administration > Extensions > Licenses, I see that the Microsoft Azure Active Directory Single Sign-On (SSO) (Pro) appears again in the table:
![image](https://user-images.githubusercontent.com/36840106/174078083-6a6b32a0-9d1d-428b-9920-e2d2c5668560.png)
Thus, I need to restart the uninstall process of the AzureAD app, plus all its' four dependencies.

 So then, all four dependency extensions seem to need to be uninstalled for a complete removal: **Configuration Pages for Microsoft Azure Active Directory Single Sign-On (SSO) (Pro)**, **Identity OAuth (Pro)**, **Microsoft Azure Active Directory Single Sign-On (SSO) (pro) API** and **Identity OAuth Integration (API)**.

**Comment by AndreeaChi** [comment]
I have updated the installation page on the app store with the need to uninstall these four dependencies when wanting to uninstall the Azure AD application. https://store.xwiki.com/xwiki/bin/view/Extension/MicrosoftAzureSSO/#installation

**Comment by oanalavinia** [comment]
These problems are caused by an Identity OAuth issue https://github.com/xwikisas/identity-oauth/issues/12
So after the fix is applied, it should be enough to only uninstall the `Microsoft Azure Active Directory Single Sign-On (SSO) (Pro)` for the login to work properly.

**Note** that when you uninstall `Microsoft Azure Active Directory Single Sign-On (SSO) (Pro)`, the `AzureAD.AzureADConfig` page is not marked by default to be deleted (since it was modified when Azure account information was added) and should be manually checked . See the screenshot below
![uninstallAzureAD](https://user-images.githubusercontent.com/22794181/182630535-48264ad8-228a-4c44-bf34-6ab3d9801382.png)
In case the application was uninstalled and you forgot to check for the `AzureAD.AzureADConfig` page to be deleted, you can still delete it manually for the uninstall to be complete.
