### ISSUE TITLE
Setting the scope of the ConfigurableClass of the AzureADConfig page to 'wiki level' breaks authentication on XWiki 13.7+

### ISSUE THREAD

**Issue by lucaa** [xwikisas/integration-azure-oauth#14]
Steps to reproduce (on XWiki 13.7+):
* go to page AzureAD.AzureADConfig
* edit in object mode
* in the XWiki.ConfigurableClass object, set the property 'scope' to 'Wiki'
* save
* configure the AzureAD authentication (if not configured already)
* try to authenticate

Expected result:
* authentication works, going though microsoft

Actual result:
* the user is redirected to microsoft to login but then, upon redirect back to XWiki, they get the login page again with the following error:

![image](https://user-images.githubusercontent.com/657716/182549334-8cc9eb1d-97e9-45ba-a6a5-0748f77fa35c.png)

**Comment by lucaa** [comment]
The cause of this issue is https://github.com/xwikisas/identity-oauth/issues/11 .

**Comment by lucaa** [comment]
Note that for 'normal' usage of this application the `scope` property of the ConfigurableClass doesn't need to be set. 
However, since the this application relies on a deprecated property (`configureGlobally`) to show the configuration section in the administration, in some situations that property can be unset and thus, in order to get the Azure AD configurable properly, the `scope` needs to be set manually. This was my case above, I exported the config page from one wiki and tried to import it in another wiki and it appears like the `configureGlobally` property got lost upon this transfer.

**Comment by oanalavinia** [comment]
This was fixed by upgrading the identity-oauth dependency in https://github.com/xwikisas/integration-azure-oauth/commit/b2dd72e76c7e2cb5264464c359ceff2a88d1d1e7 , which contains a fix for https://github.com/xwikisas/identity-oauth/issues/11
