### ISSUE TITLE
Login button is missing since 1.5.6 version

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/integration-azure-oauth#23]
Hi. I have installed the Azure AD app 1.5.7 (configuration is optional, I tested both scenarios of configured and not configured) and the Login button is missing. 
<img width="725" alt="image" src="https://user-images.githubusercontent.com/36840106/206441679-d4e6271c-24c9-485e-8bde-946ebf78d9f3.png">

I have downgraded it to 1.5.6 it was still missing:

<img width="641" alt="image" src="https://user-images.githubusercontent.com/36840106/206441877-75c60ffb-847e-405c-873e-a6fd78e91ced.png">
<img width="845" alt="image" src="https://user-images.githubusercontent.com/36840106/206441938-0c458d8e-38f5-4f59-b852-d35197ec7146.png">

However, after the downgrade to 1.5.5, the Login button was shown.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/36840106/206442128-99572f2a-4d7d-4185-b512-9ce83a5e8c18.png">
<img width="839" alt="image" src="https://user-images.githubusercontent.com/36840106/206438742-010aa8e2-8953-4be1-8eea-5e97becc8eed.png">

I tested the opposite situation of installing 1.5.5 version (Login button shown), upgraded to 1.5.6 (Login button not shown), upgraded to 1.5.7 (Login button still not shown).

I have tested on both a local XWiki Jetty 14.10 and a hosted XWiki instance, 14.4.6.

**Comment by oanalavinia** [comment]
A temporal workaround for now is to save the Identity OAuth configuration page https://github.com/xwikisas/identity-oauth/issues/18#issuecomment-1313298795

**Comment by oanalavinia** [comment]
Fixed by upgrading the dependency of Identity OAuth d3cee388f57a05b1ba728b869c81052a9432e2f1
