### ISSUE TITLE
Authentication does not work due to failed redirection when AzureAD is set as Default Provider in the IdentityOAuth

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/integration-azure-oauth#36]
Steps to reproduce:

1. Start a local XWiki 15.10.1 with Microsoft Azure AD Pro version v1.7.3 set according to the [official documentation](https://store.xwiki.com/xwiki/bin/view/Extension/MicrosoftAzureSSO/#documentation), 
2. Set the Identity OAuth Default Provider to AzureAD, 
3. Try to login with an Azure AD user, agree with the permissions 

Expected result: you are logged in on the wiki

Actual result: you are shown a page with a redirect related error without being redirected to the wiki (note that the Redirect URI is the same one set on both Microsoft Azure AD side and XWiki Azure AD settings):

<img width="1221" alt="image" src="https://github.com/xwikisas/integration-azure-oauth/assets/36840106/8f63a32e-67a6-458f-b3ea-c26136cde3fd">

**Comment by AndreeaChi** [comment]
The issue does not happen when not having the Default Provider set to a specific value. 
<img width="860" alt="image" src="https://github.com/xwikisas/integration-azure-oauth/assets/36840106/7ab0c5e6-27a5-4a7e-a19d-93a085c59239">
I'm able to login with an Azure AD user on the wiki.

**Comment by AndreeaChi** [comment]
It reproduces on Incognito as well:
<img width="1262" alt="image" src="https://github.com/xwikisas/integration-azure-oauth/assets/36840106/0ce11aa7-20b2-48a6-bfef-d3b68639c3ca">

**Comment by oanalavinia** [comment]
I released a new version of the application, [1.7.4](https://github.com/xwikisas/integration-azure-oauth/milestone/20), which should have the encryption key issue fixed. Can you check on your side if the issue is reproducing with the new version? You don't have to set a value for the encryption key anymore. Thanks!

**Comment by AndreeaChi** [comment]
I confirm that this issue does not reproduce anymore with the Microsoft Azure AD Pro 1.7.4 version. Thank you for the fix, @oanalavinia !
