### ISSUE TITLE
Add the possibility to log in with XWiki authentication service

### ISSUE THREAD

**Issue by ChiuchiuSorin** [xwikisas/integration-azure-oauth#49]
Currently, the interface that provides the option to log in with either XWiki or Microsoft Azure is generated by [Identity OAuth application](https://github.com/xwikisas/identity-oauth/blob/master/ui/src/main/resources/IdentityOAuth/LoginUIExtension.xml), but this will be removed after the [OIDC integration](https://github.com/xwikisas/integration-azure-oauth/issues/48). Currently, OIDC does not provide the option to select the standard [authenticator](https://www.xwiki.org/xwiki/bin/view/Documentation/AdminGuide/Authentication/) at login, unless an additional parameter is added to the login URL (http://localhost:8080/xwiki/bin/login/XWiki/XWikiLogin?oidc.skipped=true).

A possible workaround would be to create a [Drawer Header Item extension point](https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/ExtensionPoint/DrawerHeaderItem) to add an additional login option for using the XWiki authenticator. In this case, a new Azure configuration class should be added to provide the option for the admins to display or not the additional login option.

**Comment by snazare** [comment]
from Thomas: to look at REST use case: an alternative to BASIC is now to [use tokens](https://extensions.xwiki.org/xwiki/bin/view/Extension/OpenID%20Connect/OpenID%20Connect%20Provider/#HToken-basedaccess), in which case you don't need to skip OIDC as long as you have a token in the request (the token is checked first).

**Comment by oanalavinia** [comment]
@ChiuchiuSorin can you please add a comment to explain why this was closed as not planned? Thanks! :)
