### ISSUE TITLE
Update link to installation instructions in AzureAD Integration Configuration

### ISSUE THREAD

**Issue by silviamacovei** [xwikisas/integration-azure-oauth#9]
The link to the installation instructions in AzureAD Integration Configuration points to https://store.xwiki.com/xwiki/bin/view/Extension/AzureADIntegration#installation ATM. It should now go to https://store.xwiki.com/xwiki/bin/view/Extension/MicrosoftAzureSSO/#documentation

**Comment by polx** [comment]
Fixed in 1.5.1.
